packages:
    - internal/*
    - packages/*
    - apps/*
    - '!**/test/**'
allowBuilds:
    vue-demi: true
overrides:
    vite: 'catalog:'
catalog:
    '@catppuccin/vitepress': ^0.1.2
    '@date-fns/utc': ^2.1.1
    '@iconify-json/bi': ^1.2.7
    '@iconify-json/bx': ^1.2.3
    '@iconify-json/bytesize': ^1.2.2
    '@iconify-json/carbon': ^1.2.27
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/codicon': ^1.2.73
    '@iconify-json/devicon': ^1.2.67
    '@iconify-json/devicon-plain': ^1.2.61
    '@iconify-json/fa6-brands': ^1.2.6
    '@iconify-json/icons8': ^1.2.1
    '@iconify-json/lineicons': ^1.2.6
    '@iconify-json/logos': ^1.2.14
    '@iconify-json/material-symbols': ^1.2.93
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/mingcute': ^1.2.8
    '@iconify-json/simple-icons': ^1.2.97
    '@iconify-json/skill-icons': ^1.2.4
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/tabler': ^1.2.39
    '@iconify-json/uis': ^1.2.3
    '@iconify-json/vscode-icons': ^1.2.77
    '@iconify-json/zondicons': ^1.2.2
    '@iconify/vue': ^5.0.1
    '@napi-rs/pinyin': ^1.7.7
    '@tailwindcss/postcss': ^4.3.3
    '@tailwindcss/vite': ^4.3.3
    '@types/markdown-it': ^14.1.2
    '@types/node': ^24.13.3
    '@unhead/vue': 3.0.0-beta.6
    '@vitejs/plugin-vue': ^6.0.7
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^14.3.0
    '@vueuse/integrations': ^14.3.0
    bestzip: ^3.0.1
    date-fns: ^4.4.0
    es-toolkit: ^1.49.0
    genshin-db: ^5.2.13
    glob: ^13.0.6
    gray-matter: ^4.0.3
    gsap: ^3.15.0
    markdown-it: ^14.3.0
    markdown-it-mathjax3: ^4.3.2
    oxfmt: ^0.45.0
    oxlint: ^1.73.0
    path-to-regexp: ^8.4.2
    qrcode: ^1.5.4
    reka-ui: ^2.10.1
    syncpack: ^14.3.1
    tailwindcss: ^4.3.3
    taze: ^19.14.1
    typescript: ~5.9.3
    unplugin-icons: ^24.0.0
    uuid: ^13.0.2
    vite: ^8.1.4
    vitepress: 2.0.0-alpha.18
    vitepress-plugin-group-icons: ^1.7.6
    vue: ^3.5.39
    vue-router: ^4.6.4
    vue-tsc: ^3.3.7
