import { RcFile } from 'syncpack';

export default {
    sortFirst: [
        'name',
        'version',
        'private',
        'type',
        'files',
        'sideEffects',
        'exports',
        'scripts',
        'dependencies',
        'devDependencies',
        'peerDependencies',
        'optionalDependencies',
    ],
    versionGroups: [
        {
            label: '`workspace:*` packages',
            pinVersion: 'workspace:*',
            dependencies: ['@navifox/*'],
        },
        {
            label: '`catalog:` packages',
            pinVersion: 'catalog:',
            dependencies: [
                '@iconify/vue',
                '@tailwindcss/vite',
                '@types/markdown-it',
                '@types/node',
                '@unhead/vue',
                '@vitejs/plugin-vue',
                '@vue/tsconfig',
                '@vueuse/core',
                'bestzip',
                'es-toolkit',
                'genshin-db',
                'gsap',
                'markdown-it',
                'reka-ui',
                'tailwindcss',
                'typescript',
                'uuid',
                'vite',
                'vue',
                'vue-router',
                'vue-tsc',
            ],
        },
    ],
} satisfies RcFile;
