import type { Friend } from '@navifox/types';
import { newDate } from '@navifox/utils/dnt';

import { navifox } from './website';

export const friends: Friend[] = [
    {
        text: 'Ramid',
        link: 'https://rabbitmind.net/',
        icon: 'https://rabbitmind.net/favicon.ico',
        descriptionPure: '这里的更新速度取决于咖啡浓度☕',
        author: '若米',
        note: 'Ramid',
        avatar: 'https://rabbitmind.net/favicon.ico',
        type: 'partner',
    },
    {
        text: '纸鹿摸鱼处',
        link: 'https://blog.zhilu.site/',
        icon: 'https://www.zhilu.site/api/avatar.png',
        descriptionPure: '纸鹿至麓不知路，支炉制露不止漉。',
        author: '纸鹿',
        note: '摸鱼处',
        avatar: 'https://www.zhilu.site/api/avatar.png',
        avatarShape: 'rounded',
        type: 'feed',
        meet: newDate(2025, 7, 14),
    },
    {
        text: 'Pinpe 的云端',
        link: 'https://pinpe.top/',
        icon: 'https://pinpe.top/favicon/logo.jpg',
        descriptionPure: '宁为鲜花而死，不为面包而活。',
        author: 'Pinpe',
        note: '的云端',
        avatar: 'https://pinpe.top/head.jpg',
        avatarShape: 'rounded',
        type: 'pixel',
        meet: newDate(2025, 7, 14),
    },
    {
        text: '小白空间站',
        link: 'https://www.fatxiaobai.top',
        icon: 'https://www.fatxiaobai.top/favicon.ico',
        descriptionPure: '爱健身，爱科技，爱生活！',
        author: '胖小白',
        avatar: 'https://www.fatxiaobai.top/proxy-api/public/file/avatar/avatar.jpg',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 6, 9),
    },
    {
        text: '幽狐阁',
        link: 'https://youhuge.site/',
        icon: 'https://youhuge.site/usr/themes/handsome/assets/img/avatar.png',
        descriptionPure: '只有分离后才能懂的事，却没有了感慨的时间。',
        author: '幽悠ouo',
        note: '幽狐阁',
        avatar: 'https://youhuge.site/usr/themes/handsome/assets/img/avatar.png',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: '林の窝',
        link: 'https://www.crazying-dev.top/',
        author: '林',
        note: 'の窝',
        avatar: 'https://img.crazying-dev.top/crazying-dev.top/me.png',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: 'UnknownMp 的主站',
        link: 'https://www.unknownmp.top/',
        descriptionPure: 'qwq',
        author: 'UnknownMp',
        note: '的主站',
        avatar: 'https://www.unknownmp.top/images/self/avatar.jpg',
        avatarShape: 'rounded',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: navifox.text,
        link: '/',
        descriptionPure: navifox.status,
        author: navifox.author,
        avatar: navifox.avatar256,
        avatarShape: 'rounded',
        type: 'partner',
    },
];
