import type { Friend } from '@navifox/types';
import { newDate } from '@navifox/utils/dnt';

import { navifox } from './website';

export const friends: Friend[] = [
    {
        text: 'Ramid',
        link: 'https://rabbitmind.net/',
        icon: 'https://rabbitmind.net/favicon.ico',
        descriptionPure: '这里的更新速度取决于咖啡浓度☕',
        author: '若米',
        deck: 'Ramid',
        avatar: 'https://rabbitmind.net/favicon.ico',
        avatarShape: 'square',
        type: 'partner',
    },
    {
        text: '纸鹿摸鱼处',
        link: 'https://blog.zhilu.site/',
        icon: 'https://www.zhilu.site/api/avatar.png',
        descriptionPure: '纸鹿至麓不知路，支炉制露不止漉。',
        author: '纸鹿',
        deck: '摸鱼处',
        avatar: 'https://www.zhilu.site/api/avatar.png',
        avatarShape: 'rounded',
        type: 'feed',
        meet: newDate(2025, 1, 7),
    },
    {
        text: 'Pinpe 的云端',
        link: 'https://pinpe.top/',
        icon: 'https://pinpe.top/favicon/logo.jpg',
        descriptionPure: '宁为鲜花而死，不为面包而活。',
        author: 'Pinpe',
        deck: '的云端',
        avatar: 'https://pinpe.top/head.jpg',
        avatarShape: 'rounded',
        type: 'pixel',
        meet: newDate(2025, 7, 9),
    },
    {
        text: '渣渣120',
        link: 'https://zhazha120.cn/',
        tags: ['毛茸茸', '100.00% 狗'],
        avatar: `${navifox.link}/zhazha.svg`,
        avatarShape: 'square',
        type: 'pixel',
        meet: newDate(2026, 3, 27),
    },
    {
        text: '小白空间站',
        link: 'https://www.fatxiaobai.top',
        icon: 'https://www.fatxiaobai.top/favicon.ico',
        descriptionPure: '爱健身，爱科技，爱生活！',
        author: '胖小白',
        avatar: 'https://www.fatxiaobai.top/proxy-api/public/file/avatar/avatar.jpg',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 6, 9),
    },
    {
        text: '幽狐阁',
        link: 'https://youhuge.site/',
        icon: 'https://youhuge.site/usr/uploads/site/logo.jpg',
        descriptionPure: '回望来时路，眺看身前道',
        author: '幽悠ouo',
        deck: '幽狐阁',
        avatar: 'https://youhuhu-cdn.funtime-uwu.fun/img/-7559907791637923290.suf.jpg',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: '林の窝',
        link: 'https://www.crazying-dev.top/',
        author: '林',
        deck: 'の窝',
        avatar: 'https://img.crazying-dev.top/crazying-dev.top/me.png',
        avatarShape: 'circle',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: 'UnknownMp 的主站',
        link: 'https://www.unknownmp.top/',
        descriptionPure: 'qwq',
        author: 'UnknownMp',
        deck: '的主站',
        avatar: 'https://www.unknownmp.top/images/self/avatar.jpg',
        avatarShape: 'rounded',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
    },
    {
        text: '森雨 RainMorime',
        link: 'https://www.rainmorime.com/',
        author: '森雨',
        tags: ['显卡杀手'],
        note: '炫酷的机能风控制台。',
        deck: 'RainMorime',
        avatar: 'https://www.rainmorime.com/avatar.jpg',
        avatarShape: 'rounded',
        type: 'feed',
        meet: newDate(2026, 9, 25),
    },
    {
        text: 'Dracowyn',
        link: 'https://dracowyn.com/',
        icon: 'https://dracowyn.com/favicon-96.png',
        descriptionPure: '愿飞龙常入你梦乡',
        tags: ['显卡杀手', '毛茸茸'],
        note: '清爽、活泼、鲜明，一见钟情。',
        avatar: 'https://dracowyn.com/_astro/cover.DX1xHEdT_UBAAh.webp',
        avatarShape: 'square',
        type: 'feed',
        meet: newDate(2026, 9, 26),
    },
    {
        text: navifox.text,
        link: navifox.link,
        author: navifox.author,
        descriptionPure: navifox.status,
        tags: ['毛茸茸'],
        avatar: navifox.avatar256,
        avatarShape: 'rounded',
        type: 'partner',
    },
];
