import type { Friend } from '@navifox/types';
import { newDate } from '@navifox/utils/dnt';

export const friends: Friend[] = [
    {
        text: 'Ramid',
        link: 'https://rabbitmind.net/',
        icon: 'https://rabbitmind.net/favicon.ico',
        description: '这里的更新速度取决于咖啡浓度☕',
        author: '若米',
        note: 'Ramid',
        avatar: 'https://rabbitmind.net/favicon.ico',
        type: 'partner',
    },
    {
        text: '纸鹿摸鱼处',
        link: 'https://blog.zhilu.site/',
        icon: 'https://www.zhilu.site/api/avatar.png',
        description: '纸鹿至麓不知路，支炉制露不止漉。',
        author: '纸鹿',
        note: '摸鱼处',
        avatar: 'https://www.zhilu.site/api/avatar.png',
        type: 'feed',
        meet: newDate(2025, 7, 14),
        avatarStyles: 'rounded-2xl',
    },
    {
        text: 'Pinpe 的云端',
        link: 'https://pinpe.top/',
        icon: 'https://pinpe.top/favicon/logo.jpg',
        description: '宁为鲜花而死，不为面包而活。',
        author: 'Pinpe',
        note: '的云端',
        avatar: 'https://pinpe.top/head.jpg',
        type: 'pixel',
        meet: newDate(2025, 7, 14),
        avatarStyles: 'rounded-full',
    },
    {
        text: '小白空间站',
        link: 'https://www.fatxiaobai.top',
        icon: 'https://www.fatxiaobai.top/favicon.ico',
        description: '爱健身，爱科技，爱生活！',
        author: '胖小白',
        avatar: 'https://www.fatxiaobai.top/proxy-api/public/file/avatar/avatar.jpg',
        type: 'pixel',
        meet: newDate(2026, 6, 9),
        avatarStyles: 'rounded-full',
    },
    {
        text: '幽狐阁',
        link: 'https://youhuge.site/',
        icon: 'https://youhuge.site/usr/themes/handsome/assets/img/avatar.png',
        description: '只有分离后才能懂的事，却没有了感慨的时间。',
        author: '幽悠ouo',
        note: '幽狐阁',
        avatar: 'https://youhuge.site/usr/themes/handsome/assets/img/avatar.png',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
        avatarStyles: 'rounded-full',
    },
    {
        text: '林の窝',
        link: 'https://www.crazying-dev.top/',
        author: '林',
        note: 'の窝',
        avatar: 'https://img.crazying-dev.top/crazying-dev.top/me.png',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
        avatarStyles: 'rounded-full',
    },
    {
        text: 'UnknownMp 的主站',
        link: 'https://www.unknownmp.top/',
        description: 'qwq',
        author: 'UnknownMp',
        note: '的主站',
        avatar: 'https://www.unknownmp.top/images/self/avatar.jpg',
        type: 'pixel',
        meet: newDate(2026, 9, 10),
        avatarStyles: 'rounded-2xl',
    },
    {
        text: '路狐领航',
        link: '/',
        descriptionRich: '<code>/tp @e[type=#furry,distance=0..] @s</code>',
        author: '阿羽',
        avatar: 'https://www.navifox.net/avatar256.jpg',
        type: 'pixel',
        meet: new Date(),
        avatarStyles: 'rounded-2xl',
    },
];
